services:
  ros_follow_line:
    image: ros_follow_line
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: ros_follow_line_container
    environment:
      DISPLAY: $DISPLAY
      ROS_LOCALHOST_ONLY: 1
    privileged: true
    volumes:
      # X11
      - ~/.Xauthority:/root/.Xauthority
      # 
      - /dev/:/dev
      - .:/ws/src/ros_follow_line/
    network_mode: "host"
    command: tail -f /dev/null